name: Update Release Assets

on:
  push:
    branches:
      - main

jobs:
  create-and-update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Create ZIP files
        run: |
          # Create ZIP for individual directories
          zip -r omission.zip omission
          zip -r operant_FR.zip operant_FR
          zip -r operant_VI.zip operant_VI
          zip -r operant_PR.zip operant_PR
          
          # Create a temporary directory for operant_suite
          mkdir operant_suite
          cp -r omission operant_FR operant_VI operant_PR operant_suite/
          zip -r operant_suite.zip operant_suite

      - name: Update release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the release ID for the v1.0.1 tag
          RELEASE_ID=$(gh release view v1.0.1 --json id --jq .id)
          
          # Delete existing assets for the release (if any)
          gh release delete-asset v1.0.1 omission.zip --yes || true
          gh release delete-asset v1.0.1 operant_FR.zip --yes || true
          gh release delete-asset v1.0.1 operant_VI.zip --yes || true
          gh release delete-asset v1.0.1 operant_PR.zip --yes || true
          gh release delete-asset v1.0.1 operant_suite.zip --yes || true
          
          # Upload new assets
          gh release upload v1.0.1 \
            omission.zip \
            operant_FR.zip \
            operant_VI.zip \
            operant_PR.zip \
            operant_suite.zip
